# Generated by Django 5.0.4 on 2024-04-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emobilispage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emobilispage',
            old_name='coursename',
            new_name='studcourse',
        ),
        migrations.RenameField(
            model_name='emobilispage',
            old_name='firstname',
            new_name='studfname',
        ),
        migrations.RenameField(
            model_name='emobilispage',
            old_name='lastname',
            new_name='studlname',
        ),
        migrations.RemoveField(
            model_name='emobilispage',
            name='age',
        ),
        migrations.AddField(
            model_name='emobilispage',
            name='studemail',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
